---
- hosts: webservers
  gather_facts: yes
  become: yes
  # vars:
  #   app_path: app.py
  #   app_command: "{{ app_path }}.py"

  tasks:
    # - debug:
    #     var: ansible_default_ipv4.address
    - name: Upadate cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install Python and pip
      apt:
        name:
          - python3
          - python3-pip
        state: latest

    - name: Install Flask
      pip:
        name: flask
        state: latest

    - name: Stop SNMPd service
      service:
        name: snmpd
        state: stopped
      ignore_errors: yes  # SNMPd might not be installed initially

    - name: Remove SNMPd packages
      apt:
        name: 
          - snmpd
        state: absent
        autoremove: yes
        purge: true

    - name: Install SNMPd package
      package: name=snmpd state=latest

    # - name: Stop SNMP service
    #   service:
    #     name: snmp
    #     state: stopped
    #   ignore_errors: yes  # SNMPd might not be installed initially

    - name: Remove SNMP packages
      apt:
        name: 
          - snmp
        state: absent
        autoremove: yes
        purge: true

    - name: Install SNMP package
      package: name=snmp state=latest

    - name: Copy snmpd conf file
      copy:
        src: ./snmpd.conf
        dest: /etc/snmp/snmpd.conf
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Restart snmpd
      service: name=snmpd state=restarted
    - name: copy app.py
      copy:
        src: ./app.py 
        dest: /home/ubuntu
        owner: ubuntu
        group: ubuntu
        mode: 0644
    - name: Running flask app
      shell: python3 /home/ubuntu/app.py 
      async: 3600
      poll: 0


- hosts: haproxy
  gather_facts: yes
  become: yes

  tasks:
    - name: Upadate cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Stop HAproxy service
      service:
        name: haproxy
        state: stopped
      ignore_errors: yes  # HAproxy might not be installed initially

    - name: Remove HAproxy packages
      apt:
        name: 
          - haproxy
        state: absent
        autoremove: yes
        purge: true

    - name: Install HAproxy
      apt:
        name: haproxy
        state: present    
    - name: Copy HAproxy configuration file
      ansible.builtin.template:
        src: ./haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
    - name: Restart HAProxy
      service: name=haproxy state=restarted

    - name: Stop NGINX service
      service:
        name: nginx
        state: stopped
      ignore_errors: yes  # NGINX might not be installed initially

    - name: Remove NGINX packages
      apt:
        name: 
          - nginx
          # - nginx-full
          # - nginx-common
        state: absent
        autoremove: yes
        purge: true
    
    - name: Install Nginx package
      package: name=nginx state=latest
      # package:
      #   name: nginx
      #   state: latest
    - name: Copy Nginx configuration file
      ansible.builtin.template:
        src: ./nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        owner: ubuntu
        group: ubuntu
        mode: '0644'
    - name: Copy Nginx default file to sites-enabled
      copy:
        src: ./default
        dest: /etc/nginx/sites-enabled/default
        owner: ubuntu
        group: ubuntu
        mode: '0644'
    - name: Copy Nginx default file to sites-available
      copy:
        src: ./default
        dest: /etc/nginx/sites-available/default
        owner: ubuntu
        group: ubuntu
        mode: '0644'
    - name: Restart Nginx service
      service: name=nginx state=restarted

    - name: Copy password file
      copy:
        src: ./uipassword
        dest: /etc/haproxy/
        owner: ubuntu
        group: ubuntu
        mode: 0777
    - name: Remove SNMP packages
      apt:
        name: 
          - snmp
        state: absent
        autoremove: yes
        purge: true           
    - name: Install SNMP package
      package: name=snmp state=latest